# config/config.yaml
models:
  idea_generation:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.7
  
  topic_analysis:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.5  # Lower temperature for more focused analysis
  
  abstract_development:
    provider: openai
    model: gpt-4-turbo-preview
    max_tokens: 4000
    temperature: 0.7
    
  argument_development:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.6

  outline_assembly:
    provider: openai
    model: gpt-4-turbo-preview
    max_tokens: 4000
    temperature: 0.6
    
  structure_planning:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.6
    
  section_development:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.7
    
  final_selection:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.5  # Lower temperature for more focused selection
    
  outline_improvement:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.7
    
  outline_critique:
    provider: openai
    model: o1-mini  # Use o1 for critical analysis
    max_tokens: 20000
    temperature: 1
    
  outline_refinement:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.6
    
  formal_development:
    provider: openai
    model: o1-mini
    max_tokens: 20000
    temperature: 1
    
  formal_refinement:
    provider: openai
    model: o1-mini
    max_tokens: 20000
    temperature: 1
    
  example_enhancement:
    provider: openai
    model: o1-mini
    max_tokens: 20000
    temperature: 1
    
  clarity_verification:
    provider: openai
    model: gpt-4-turbo-preview
    max_tokens: 4000
    temperature: 0.7
  
  synthesis:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.5  # Lower temperature for more focused synthesis
      
  json_repair:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    max_tokens: 8192
    temperature: 0.2
    

    



paths:
  base_dir: ./outputs
  generated_topics: generated_topics.json
  topics_culled: topics_culled.json
  topic_analysis: topic_analysis.json
  abstracts: topic_abstracts.json
  arguments: argument_development.json
  outlines: detailed_outlines.json
  final_selection: final_selection.json
  outline_development_state: outline_development_state.json
  #outline_development: current_outline.md
  outline_development: outline.md
  outline_development_state: outline_development_state.json

parameters:
  num_initial_topics: 8 # topic ideas to generate initially for brainstorming 
  max_selected_topics: 3 # max number of ideas left over after initial cull
  abstract_length: 300
  outline_sections: 6  # approximate number of major sections
  development_stages: 5  # number of API calls per topic
  outline_development_cycles: 3  